services:
  ollama-service:
    image: ollama/ollama:latest
    container_name: ollama_container
    restart: unless-stopped
    volumes:
      - ollama-data:/root/.ollama
    runtime: nvidia
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_MODELS=/root/.ollama/models
      - NVIDIA_VISIBLE_DEVICES=all
    #entrypoint: /bin/sh
    #command: -c "ollama serve & sleep 5 && ollama pull qwen3:latest && wait" ## para descargar el modelo al iniciar el contenedor
    networks:
      - app_net


  spring-boot-service-ms-suggestions:
    container_name: ms-suggestions-app
    image: ms-suggestions
    restart: unless-stopped
    build:
      context: ./ms-suggestions
      dockerfile: ms-suggestions/Dockerfile
    depends_on:
      - ollama-service
      - spring-boot-service-ms-api-gateway
    environment:
      - SPRING_AI_OLLAMA_BASE_URL=http://ollama-service:11434
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_AI_OLLAMA_MODEL=qwen3:latest
    networks:
      - app_net

  spring-boot-service-ms-api-gateway:
    container_name: ms-api-gateway-app
    image: ms-api-gateway
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ms-api-gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app_net


volumes:
  ollama-data:

networks:
  app_net:
    driver: bridge