spring:
  config:
    activate:
      on-profile: dev

ollama:
  base-url: "http://localhost:11434"
  connect-timeout-ms: 60000
  response-timeout-s: 300
  llama:
    model: "qwen3:latest"
    temperature: 0.6
    numPredict: 1024
    keepAlive: "10m"
