spring:
  application:
    name: api-gateway
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
      base-path: /actuator

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: ms-suggestions
        url: /suggestions/api-docs
