spring:
  config:
    activate:
      on-profile: dev

  cloud:
    gateway:
      routes:
        - id: ms-suggestions-recommender-stream
          uri: http://spring-boot-service-ms-suggestions:8081
          predicates:
            - Path=/ai/recommender/stream
          filters:
            - RewritePath=/ai/recommender/stream, /ai/recommender/stream
        - id: ms-suggestions-recommender-sync
          uri: http://spring-boot-service-ms-suggestions:8081
          predicates:
            - Path=/ai/recommender/sync
          filters:
            - RewritePath=/ai/recommender/sync, /ai/recommender/sync